####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude 
  elevation: 23
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include_dir_merge_named customize/

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
   api_password: !secret api_password
   base_url: !secret base_url
   # Lets Encrypt certs
   ssl_certificate: !secret ssl_certificate
   ssl_key: !secret ssl_key
   #Run on specified port
   server_port: !secret server_port

updater:
discovery:
conversation:
history:
logbook:
sun:
wake_on_lan:
tts:
  - platform: google

group: !include groups.yaml
script: !include scripts.yaml
light: !include light.yaml
sensor: !include sensor.yaml
#device_tracker: !include device_tracker.yaml
media_player: !include media_player.yaml
switch: !include switch.yaml
automation: !include_dir_merge_list automation/
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
scene: !include scenes.yaml
input_boolean: !include input_boolean.yaml

#Enable iOS component
ios:

#Enable HomeKit to use Siri
homekit:
  filter:
    exclude_domains:
      - binary_sensor
      - automation
#Enable Dark Sky
weather:
  - platform: darksky
    api_key: !secret darkskyapi
#https://home-assistant.io/components/recorder/
recorder:
  purge_interval: 1
  purge_keep_days: 3

#https://home-assistant.io/components/logger/
logger:
  default: error
  logs:
    homeassistant.components.sensor.template: critical
    homeassistant.components.cover: critical
